code --install-extension denoland.vscode-deno
code --install-extension exodiusstudios.comment-anchors
code --install-extension icrawl.discord-vscode
code --install-extension ms-azuretools.vscode-docker
code --install-extension dbaeumer.vscode-eslint
code --install-extension golang.go
code --install-extension graphql.vscode-graphql
code --install-extension ritwickdey.liveserver
code --install-extension pkief.material-icon-theme
code --install-extension sdras.night-owl
code --install-extension chris-noring.node-snippets
code --install-extension eg2.vscode-npm-script
code --install-extension christian-kohler.npm-intellisense
code --install-extension rust-lang.rust
code --install-extension formulahendry.terminal
code --install-extension infeng.vscode-react-typescript
code --install-extension vscodevim.vim
code --install-extension gamunu.vscode-yarn
code --install-extension benawad.vsinder
