code --install extension aaron-bond.better-comments
code --install extension ms-azuretools.vscode-docker
code --install extension dbaeumer.vscode-eslint
code --install extension github.github-vscode-theme
code --install extension golang.go
code --install extension kumar-harsh.graphql-for-vscode
code --install extension ms-toolsai.jupyter 
code --install extension ritwickdey.liveserver
code --install extension pkief.material-icon-theme
code --install extension chris-noring.node-snippets
code --install extension esbenp.prettier-vscode
code --install extension ms-python.python
code --install extension formulahendry.terminal
code --install extension vscodevim.vim
code --install extension gamunu.vscode-yarn
code --install extension visualstudioexptteam.vscodeintellicode