code --install extension d-exclaimation.liveride-color-theme
code --install extension golang.go
code --install extension kumar-harsh.graphql-for-vscode
code --install extension saratravi.elixir-formatter
code --install extension ritwickdey.liveserver
code --install extension pkief.material-icon-theme
code --install extension chris-noring.node-snippets
code --install extension esbenp.prettier-vscode
code --install extension jakebecker.elixir-ls
code --install extension formulahendry.terminal
code --install extension vscodevim.vim
code --install extension gamunu.vscode-yarn
code --install extension visualstudioexptteam.vscodeintellicode